# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
. "$HOME/.cargo/env"

export PATH=$PATH:~/.local/share/bin/
eval "$(zoxide init bash)"
eval "$(zellij setup --generate-auto-start bash)"

function cman() {
  man $1 | bat
}

function jd() {
  local file
  local dir
  local Arg_dir
  [[ $# > 1 ]] && echo "error: only should one args" && return 1
  [[ "$1" == "" ]] && Arg_dir="." || Arg_dir="$1"

  if [[ -d "$Arg_dir" ]]; then
    cd $Arg_dir
    file=$(fzf +m) && dir=$(dirname "$file") && cd "$dir"
  else
    echo "warning: dir \"$Arg_dir\" not exist";
    return 1;
  fi
}


function __HISTOR_CD__() {
  # history max num can saved
  local __Cache_Num__
  local __MAX_HISTOR_NUM__=100
  local __DIR_STACK_FILE_SETTING__="$HOME/.cache/dir_stack_file_setting.db"
  cd $@ || return $?;
  [[ "$1" == "" ]] && return 0;

  var="$(pwd)"

  grep -q "^$var$" "$__DIR_STACK_FILE_SETTING__" && return 0;

  __Cache_Num__=$(sed -n '$=' "$__DIR_STACK_FILE_SETTING__")
  if [[ __Cache_Num__ -gt $__MAX_HISTOR_NUM__ ]];then
    sed -i '1d' "$__DIR_STACK_FILE_SETTING__"
  fi
  echo $(pwd) >> "$__DIR_STACK_FILE_SETTING__"
}

alias cd='__HISTOR_CD__'

function kd() {
  local __DIR_STACK_FILE_SETTING__="$HOME/.cache/dir_stack_file_setting.db"
  result=$(cat $__DIR_STACK_FILE_SETTING__ | fzf)
  [[ "$result" == "" ]] && return 0
  cd $result
}

function fd() {
  local Arg_dir
  [[ $# > 1 ]] && echo "error: only should one args" && return 1
  [[ "$1" == "" ]] && Arg_dir="." || Arg_dir="$1"
  
  if [[ -d "$Arg_dir" ]]; then
    result=$(fdfind -t d . "$Arg_dir" | fzf +m)
    [[ "$result" == "" ]] && return 0
    cd $result
  else
    echo "warning: dir \"$Arg_dir\" not exist";
    return 1;
  fi
}
